### PR TITLE
Support tournament replays

### LINKED ISSUE #112: Error decoding frame: time is out of range
[7354f090-54ef-4bb3-8b80-10d101913b1d.zip](https://github.com/nickbabcock/boxcars/files/5308678/7354f090-54ef-4bb3-8b80-10d101913b1d.zip)

`Error decoding frame: time is out of range: 0.000000000000000000000000000000000000071193495.  Context: on frame: 1, backtracking to frame 0, last new actor: (id: 56, nameId: 56, objId: 325, objName: TAGame.Default__MaxTimeWarningData_TA, initial trajectory: Trajectory { location: None, rotation: None })`

### PR DESCRIPTION
**Pull request by nickbabcock**
Closes #112

Naming based on (ie: stolen from) bakkes: https://github.com/Bakkes/CPPRP/commit/95df0b92ea822e6e98b296fceb7918c1f2e8b7fb

minor difference: there is no difficulty in the replay (so may need another sample)

cc @Sciguymjm

### CODE REVIEW

**Comment by Sciguymjm** [comment]
[fd8f6dc8-c3e4-47a2-8640-8fcb8afbc989.zip](https://github.com/nickbabcock/boxcars/files/5309421/fd8f6dc8-c3e4-47a2-8640-8fcb8afbc989.zip)
See if any of these have what you need.

**Comment by nickbabcock** [comment]
No, but it can always be added later. That way I can ensure there is a test case for every new field we add (to prevent future regressions)

**Comment by Bakkes** [comment]
I think the difficulty int is related to parsing training replays, accidentally committed that with the tournament changes.

**Comment by nickbabcock** [comment]
Gotcha, yeah that makes sense. When I get a bug report for it, I'll add the attribute 😄

**Comment by tfausak** [comment]
I have a small replay with the `TAGame.Team_TA:Difficulty` attribute: [FFB71FEF40BA7D4E7A5C4CA9F5B8EA6F.zip](https://github.com/nickbabcock/boxcars/files/5321878/FFB71FEF40BA7D4E7A5C4CA9F5B8EA6F.zip)

It is not from training and plays normally in the latest RL client.

**Pull request merged**
